CREATE TABLE INSTRUMENT_PRICE_MODIFIER(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
                                       NAME CHAR NOT NULL,
                                       MULTIPLIER DOUBLE);

-- CREATE TRIGGER MULTIPLIER_TRIGGER AFTER UPDATE ON INSTRUMENT_PRICE_MODIFIER FOR EACH ROW CALL "com.infusion.correction.CorrectionTrigger";