CREATE SCHEMA IF NOT EXISTS INSTRUMENTS;
CREATE TABLE INSTRUMENT_PRICE_MODIFIER(ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL, NAME CHAR NOT NULL, MULTIPLIER DOUBLE);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (1, 'INSTRUMENT1', 1);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (2, 'INSTRUMENT2', 1);
INSERT INTO INSTRUMENT_PRICE_MODIFIER VALUES (3, 'INSTRUMENT3', 1);